#!/bin/bash

read -p "Enter your domain name: " domain

# Set the certificate file paths
cert_path="/etc/letsencrypt/live/${domain}.com/fullchain.pem"
privkey_path="/etc/letsencrypt/live/${domain}.com/privkey.pem"

# Check if the certificate files exist
if [ -f "$cert_path" ] && [ -f "$privkey_path" ]; then
    # Check the validity of the certificate
    if openssl x509 -checkend 0 -noout -in "$cert_path"; then
        echo "Certificate is still valid. No renewal needed."
    else
        echo "Certificate has expired or is invalid. Proceeding with renewal..."
        certbot certonly --noninteractive --agree-tos --register-unsafely-without-email \
            --dns-cloudflare --dns-cloudflare-credentials "/root/.cloudflare/token" \
            --dns-cloudflare-propagation-seconds 30 -d "${domain}.com" -d "*.${domain}.com"
    fi
    
    # Calculate the number of days left until the certificate expires
    expiry_date=$(openssl x509 -enddate -noout -in "$cert_path" | cut -d "=" -f 2)
    expiry_timestamp=$(date -d "$expiry_date" +%s)
    current_timestamp=$(date +%s)
    days_remaining=$(( (expiry_timestamp - current_timestamp) / 86400 ))
    
    echo "Days remaining until certificate expiration: $days_remaining days"
    
else
    echo "No valid certificate found for the domain. Generating a new certificate..."
    certbot certonly --noninteractive --agree-tos --register-unsafely-without-email \
        --dns-cloudflare --dns-cloudflare-credentials "/root/.cloudflare/token" \
        --dns-cloudflare-propagation-seconds 30 -d "${domain}.com" -d "*.${domain}.com"
fi
